[#34] redis blacklist 설정을 통한 로그아웃 기능 구현
BidNamu/bidnamu-backend pull request #60
Opened 2024-01-17 07:57 UTC by kimmin1kk

#34

2024-01-17 13:37 UTC, jeongmu1 requested changes
수고하셨습니다 !

2024-01-17 13:37 UTC, jeongmu1 commented on src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
> +        }
혹시 if문 안쪽을 비워두신 이유가 있을까요 ??

2024-01-17 13:37 UTC, jeongmu1 commented on src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
> +        Long expiration = tokenProvider.getExpiration(accessToken);
이 부분 final 키워드 깜빡하신 것 같아요 !

2024-01-17 13:37 UTC, jeongmu1 commented on src/main/java/com/bidnamu/bidnamubackend/auth/controller/AuthController.java
> +            requestDto.accessToken()));
로그아웃 진행 시 DTO에 있는 refreshToken은 사용되지 않는 것 같은데 이러면 굳이 DTO에서 accessToken을 꺼내오는 것 보다는 HTTP header에 있는 accessToken을 추출하여 로그아웃을 진행하는 것은 어떻게 생각하시나요 ??

2024-01-17 13:37 UTC, jeongmu1 commented on src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
> +            TimeUnit.MILLISECONDS);
redisSessionConfig.redisTemplate()로 RedisTemplate 객체를 가져오기 보다는 RedisTemplate Bean을 주입받아 사용하는 것이 맞을 것 같아요 !

2024-01-17 13:39 UTC, Hw0o0 reviewed
수고 많으셨습니다!

2024-01-18 04:24 UTC, kimmin1kk commented on src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
> +        Long expiration = tokenProvider.getExpiration(accessToken);
수정하겠습니다!

2024-01-18 04:28 UTC, kimmin1kk commented on src/main/java/com/bidnamu/bidnamubackend/auth/controller/AuthController.java
> +            requestDto.accessToken()));
그렇게 진행하려고 했었는데 제가 진행중인 브랜치에선 HTTP header bearer + accessToken을 요구하는 api가 존재하지 않아 현재 conflict 나는 부분을 해결후 develop 브랜치에 합친 후 refactor 브랜치로 진행하기 위해서 일단 그대로 둔 부분입니다!

2024-01-18 04:50 UTC, kimmin1kk commented on src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
> +        }
getClaims 내부에서 예외가 발생해서 여기선 따로 예외처리를 해도 닿지 않을 것이라 판단하여 일단 비워뒀었는데 그대로 까먹고 있었던 거 같습니다. if문을 없애는 방향으로 수정하겠습니다!

2024-01-18 05:30 UTC, kimmin1kk commented on src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
> +            TimeUnit.MILLISECONDS);
수정했습니다!

2024-01-18 11:18 UTC, kimmin1kk commented on src/main/java/com/bidnamu/bidnamubackend/auth/controller/AuthController.java
> +            requestDto.accessToken()));
수정했습니다!

2024-01-18 12:56 UTC, jeongmu1 approved these changes
수고 많으셨습니다 !!

2024-01-18 13:16 UTC, merged